//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ACS.rc
//
#define ID_Send                         2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ACS_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       131
#define IDI_ICON2                       132
#define IDI_ICON3                       134
#define IDI_ICON4                       158
#define IDD_DIALOG_MORSE                163
#define IDD_DIALOG_MORSEAUV             164
#define IDD_DIALOG_WORD                 165
#define IDB_linkon                      167
#define IDB_linkdown                    169
#define IDB_lose                        172
#define IDB_get                         174
#define IDD_DIALOG_FS                   182
#define IDB_expand                      184
#define IDB_Chart                       185
#define IDB_POST                        186
#define IDD_DIALOG_COMPARAM             187
#define IDD_PICTURE                     188
#define XPSTEEL                         192
#define Devior                          193
#define IDR_xplus                       194
#define IDR_XPGREEN                     195
#define IDR_KOMOBLUE                    196
#define futura                          197
#define IDR_TUSK                        198
#define IDD_DIALOG_POSTVIEW             205
#define IDD_DIALOG_DATA                 207
#define IDD_DIALOG_WAVEVIEW             208
#define IDD_DIALOG_ADCP                 210
#define IDB_ZOOMOUT                     212
#define IDB_ZOOMIN                      213
#define IDD_OPTIONS                     214
#define IDB_PLAY                        215
#define IDB_pause                       216
#define IDD_DIALOG_LOG                  217
#define IDD_DIALOG_AD                   218
#define IDI_LEDON                       220
#define IDI_LEDOFF                      221
#define IDD_BASIC                       222
#define IDD_ADVANCED                    223
#define IDB_ON                          232
#define IDB_OFF                         233
#define IDD_DIALOG_Tablog               234
#define IDD_DIALOG_EDITPIC              235
#define IDD_DIALOG_VIDEO                237
#define IDB_WORk                        242
#define IDC_COMBO_XMT                   1000
#define IDC_BUTTON_LOAD                 1006
#define IDC_COMBO_WORDINFO              1011
#define IDC_EDIT3                       1012
#define IDC_EDIT_EWORD                  1012
#define IDC_SAMPLE_RATE                 1012
#define IDC_Gain1                       1012
#define IDC_MPSKTrainSymbolNum          1012
#define IDC_BUTTON_SENDTEXT             1013
#define IDC_Gain2                       1013
#define IDC_MFSKInterGuardLag           1013
#define IDC_RADIO_SETWORD               1014
#define IDC_Gain3                       1014
#define IDC_ChirpLen                    1014
#define IDC_RADIO_EWORD                 1015
#define IDC_Gain4                       1015
#define IDC_ChirpStartF                 1015
#define IDC_BUTTON_CONNECT              1016
#define IDC_Gain5                       1016
#define IDC_ChirpStopF                  1016
#define IDC_BUTTON_SYSINI               1017
#define IDC_Gain6                       1017
#define IDC_InterLeaverLen              1017
#define IDC_BUTTON_DSPRUN               1018
#define IDC_BeltaMu                     1018
#define IDC_PROGRESS_RECORD             1019
#define IDC_IterationNum                1019
#define IDC_SPIN1                       1020
#define IDC_PreFilterTap                1020
#define IDC_STATIC_status               1021
#define IDC_MuMin                       1021
#define IDC_BUTTON1                     1022
#define IDC_SlideWinLen                 1022
#define IDC_BUTTON2                     1023
#define IDC_EXPAND                      1023
#define IDC_ZOOMIN                      1023
#define IDC_SavPic                      1023
#define IDC_adview3                     1023
#define IDC_AlfaPhase                   1023
#define IDC_BUTTON_CLEAR                1024
#define IDC_adview2                     1024
#define IDC_BUTTON3                     1024
#define IDC_AftFilterTap                1024
#define IDC_adview1                     1025
#define IDC_MuMax                       1025
#define IDC_ADIO_STATE_LIGHT            1026
#define IDC_adview5                     1026
#define IDC_GamaMax                     1026
#define IDC_BUTTON_MSGOK                1027
#define IDC_adview4                     1027
#define IDC_ADIO_STATE_LIGHT2           1027
#define IDC_GamaMin                     1027
#define IDC_BUTTON_MSGDN                1028
#define IDC_adview6                     1028
#define IDC_ADIO_STATE_LIGHT3           1028
#define IDC_cycle_prefix                1028
#define IDC_BUTTON_MSGUP                1029
#define IDC_ADIO_STATE_LIGHT4           1029
#define IDC_BUTTON_MSGDB                1030
#define IDC_ADIO_STATE_LIGHT5           1030
#define IDC_BUTTON_MSGWK                1031
#define IDC_BUTTON_MSGDU                1032
#define IDC_EDIT_LOG                    1033
#define IDC_BUTTON_MSGISOK              1034
#define IDC_BUTTON_MSGREP               1036
#define IDC_BUTTON_NO                   1037
#define IDC_BUTTON_ASK                  1038
#define IDC_NTGRAPHCTRL1                1039
#define IDC_NTGRAPH_ADVIEW              1039
#define IDC_BUTTON_PAUSE                1040
#define IDC_BUTTON_SAVPIC               1041
#define IDC_BUTTON_ZOOMOUT              1042
#define IDC_BUTTON_ZOOMIN               1043
#define IDC_NTGRAPHCTRL2                1044
#define IDC_POSTVIEW                    1044
#define IDC_EDIT_TALKLOG                1045
#define IDC_BUTTON_START                1046
#define IDC_BUTTON_START2               1048
#define IDC_BUTTON_START3               1049
#define IDC_BUTTON_START4               1050
#define IDC_BUTTON_START5               1051
#define IDC_OPEN_OPTION                 1051
#define IDC_BUTTON_START6               1052
#define IDC_LOG                         1052
#define IDC_POSTTIME                    1053
#define IDC_PROGRESS1                   1054
#define IDC_PROGRESS2                   1055
#define IDC_PROGRESS3                   1056
#define IDC_PROGRESS4                   1057
#define IDC_PROGRESS5                   1058
#define IDC_PROGRESS6                   1059
#define IDC_PROGRESS8                   1061
#define IDC_PROGRESS7                   1062
#define IDC_PROGRESS_VOLUME             1062
#define IDC_LIST_ADCP                   1063
#define IDC_TAB                         1066
#define IDC_ADVIEW                      1067
#define IDC_BUTTON4                     1068
#define IDC_ADREPLAY                    1068
#define IDC_BUTTON5                     1069
#define IDC_STATIC_DATA                 1070
#define IDC_POST                        1071
#define IDC_HEAD                        1072
#define IDC_DATAUPDATETIME              1073
#define IDC_ROLL                        1073
#define IDC_RICHEDIT_WORD               1074
#define IDC_PITCH                       1074
#define IDC_UWVLONG                     1075
#define IDC_EDIT_SHOWWORD               1076
#define IDC_UWVLAT                      1076
#define IDC_ADDtoLIST                   1077
#define IDC_SHIPLONG                    1077
#define IDC_SEND                        1078
#define IDC_SHIPLAT                     1078
#define ID_AddToList                    1079
#define IDC_DISTANCEX                   1079
#define IDC_EDIT_INPUT                  1080
#define IDC_DISTANCEY                   1080
#define IDC_EDIT_WORDLOG                1081
#define IDC_FRONT                       1081
#define IDC_COMBO1                      1082
#define IDC_FRONT2                      1082
#define IDC_MORSELIST                   1082
#define IDC_FRONTDOWN                   1082
#define IDC_SysWorkMode                 1082
#define IDC_COMBO_DIGITCHNNL            1082
#define IDC_SLIDER1                     1083
#define IDC_UWVDEEP                     1083
#define IDC_SLIDER2                     1084
#define IDC_FRONT4                      1084
#define IDC_LEFT                        1084
#define IDC_SLIDER3                     1085
#define IDC_FRONT5                      1085
#define IDC_RIGHT                       1085
#define IDC_SLIDER4                     1086
#define IDC_FRONT6                      1086
#define IDC_DOWN                        1086
#define IDC_SLIDER5                     1087
#define IDC_FRONT7                      1087
#define IDC_BACKDOWN                    1087
#define IDC_SLIDER6                     1088
#define IDC_UWVHEIGTH                   1088
#define IDC_CHECK                       1089
#define IDC_SLIDER7                     1089
#define IDC_ADVANCED                    1090
#define IDC_UpdateTime                  1091
#define IDC_SLIDER8                     1091
#define IDC_STATIC_UWVLONG              1098
#define IDC_STATIC_UWVLAT               1099
#define IDC_STATIC_SHIPLONG             1100
#define IDC_STATIC_SHIPLAT              1101
#define IDC_SavePic                     1106
#define IDC_SELECTPIC                   1107
#define IDC_SENDPIC                     1108
#define IDC_ZOOMOUT                     1109
#define IDC_LOOK_FLAT                   1110
#define IDC_LOOK_DOWN                   1111
#define IDC_SENDMORSE                   1112
#define IDC_STATIC_TYPE                 1113
#define IDC_STATIC1                     1114
#define IDC_STATIC2                     1115
#define IDC_STATIC3                     1116
#define IDC_STATIC4                     1117
#define IDC_STATIC5                     1118
#define IDC_TREE1                       1118
#define IDC_STATIC_TYPE2                1119
#define IDC_STATIC6                     1120
#define IDC_PAUSE                       1120
#define IDC_STATIC7                     1121
#define IDC_WAVEZOOMIN                  1121
#define IDC_STATIC8                     1122
#define IDC_WAVEZOOMOUT                 1122
#define IDC_STATIC9                     1123
#define IDC_STATIC10                    1124
#define IDC_ADSAMPLE                    1125
#define IDC_IMAGE                       1127
#define IDC_EDIT1                       1128
#define IDC_ADIO_STATUS                 1129
#define IDC_COMBO2                      1130
#define IDC_ADIOWorkMode                1130
#define IDC_GAIN                        1131
#define IDC_DESCRIB                     1132
#define IDC_SAMPLETIME                  1133
#define IDC_ADSTART                     1135
#define IDC_SLIDER_AMP                  1136
#define IDC_SLIDER_DIGITALAMP           1137
#define IDC_FRONT3                      1138
#define IDC_FRONTUP                     1138
#define IDC_STATIC_AMP                  1139
#define IDC_BUTTON_DEFAULT              1140
#define IDC_STATIC_DIGITALAMP           1140
#define IDC_BUTTON6                     1141
#define IDC_BUTTON7                     1142
#define IDC_BUTTON8                     1143
#define IDC_BUTTON9                     1144
#define IDC_BUTTON10                    1145
#define IDC_BUTTON11                    1146
#define IDC_BUTTON12                    1147
#define IDC_ADCP_UPDATETIME             1148
#define IDC_BPUpdateTime                1149
#define IDC_PARAMLIST                   1151
#define IDC_FH_SEND                     1152
#define IDC_FHWORD                      1153
#define IDC_FHLOG                       1154
#define IDC_MARINE_TEMP                 1155
#define IDC_MARINE_SALT                 1156
#define IDC_MARINE_HUMID                1156
#define IDC_SYS_STATUS                  1157
#define IDC_RECORD_STATUS               1158
#define IDC_BSSS                        1159
#define IDC_CO2                         1159
#define IDC_CH1                         1160
#define IDC_CH2                         1161
#define IDC_CH3                         1162
#define IDC_CH4                         1163
#define IDC_CH5                         1164
#define IDC_CH6                         1165
#define IDC_MARINE_O2                   1166
#define IDC_MARINE_TEMPINSIDE           1167
#define IDC_LOAD                        1168
#define IDC_CH7                         1168
#define IDC_MARINE_DOWNVEC              1169
#define IDC_CH8                         1170
#define IDC_BASIC                       1171
#define IDC_IsTCM2Work                  1173
#define IDC_DiscardLen                  1174
#define IDC_IsSendADIOData              1176
#define IDC_BeforeDecideData            1177
#define IDC_AfterDecideData             1178
#define IDC_AfterDecideBit              1179
#define IDC_ParamFactor                 1180
#define IDC_PhaseFactor                 1181
#define IDC_DopplerFactor               1182
#define IDC_IsAGCWork                   1183
#define IDC_SAMETOGAIN1                 1184
#define IDC_SyncConcurrence             1185
#define IDC_ADIOID                      1186
#define IDC_DSP01ID                     1187
#define IDC_DSP02ID                     1188
#define IDC_DSP11ID                     1189
#define IDC_DSP12ID                     1190
#define IDC_XMTAmpValue                 1191
#define IDC_XMTSampleRate               1192
#define IDC_XMTDelayToSync              1193
#define IDC_EDIT7                       1194
#define IDC_MFSK_PACKET                 1194
#define IDC_EDIT8                       1195
#define IDC_MPSK_PACKET                 1195
#define IDC_EDIT9                       1196
#define IDC_MFSK_FRAMENUM               1196
#define IDC_EDIT10                      1197
#define IDC_MPSK_FRAMENUM               1197
#define IDC_RecChannelNum               1198
#define IDC_RecvSampleRate              1199
#define IDC_RECVDELAYSYNC               1200
#define IDC_Chann1                      1201
#define IDC_Chann2                      1202
#define IDC_MPSKPreGuardLag             1202
#define IDC_Chann3                      1203
#define IDC_MPSKAftGuardLag             1203
#define IDC_Chann4                      1204
#define IDC_MPSKDataSymbolNum           1204
#define IDC_SAVE                        1204
#define IDC_Chann5                      1205
#define IDC_MFSKPreGuardLag             1205
#define IDC_Chann6                      1206
#define IDC_MFSKAftGuardLag             1206
#define IDC_TEST                        1206
#define IDC_EDIT11                      1207
#define IDC_MFSKataSymbolNum            1207
#define IDC_MFSK_RECVPACKET             1207
#define IDC_EDIT12                      1208
#define IDC_MPSK_RECVPACKET             1208
#define IDC_MPSK_chirp_inter            1208
#define IDC_EDIT13                      1209
#define IDC_MFSK_RECVFRAMENUM           1209
#define IDC_MFSK_chirp_inter            1209
#define IDC_EDIT14                      1210
#define IDC_MPSK_RECVFRAMENUM           1210
#define IDC_SAVEAS                      1211
#define IDC_RADIO_MFSK                  1212
#define IDC_RADIO_MPSK                  1213
#define IDC_RADIO_WATER                 1214
#define IDC_STATIC_p5                   1215
#define IDC_STATIC_n5                   1216
#define IDC_STATIC_p12                  1217
#define IDC_STATIC_n12                  1218
#define IDC_STATIC_r1                   1219
#define IDC_STATIC_r2                   1220
#define IDC_STATIC_send                 1221
#define IDC_STATIC_5t                   1222
#define IDC_STATIC_sw                   1223
#define IDC_STATIC_12t                  1224
#define IDC_STATIC_BASE                 1224
#define IDC_STATIC_33t                  1225
#define IDC_STATIC_24t                  1226
#define IDC_PIC_RECVTIME                1227
#define IDC_BUTTON_SETGAIN              1229
#define IDC_SetTime                     1230
#define IDC_RADIO1                      1231
#define IDC_DiSCONNECT                  1231
#define IDC_ENFORCE_SEND                1232
#define IDC_RESETADIO                   1233
#define IDC_PROGRESS9                   1234
#define IDC_STATIC_DISTANCE             1236
#define IDC_BUTTON13                    1237
#define IDC_BIN_ROLL                    1238
#define IDC_BIN_PITCH                   1239
#define IDC_BUTTON14                    1240
#define IDC_STATUS                      1241
#define IDC_MARINE_PRESSURE             1242
#define IDC_MAIN_V                      1243
#define IDC_MAIN_I                      1244
#define IDC_MARINE_DEPTH                1245
#define IDC_MARINE_HEIGTH               1246
#define IDC_BUTTON_SELECT               1247
#define IDC_STATIC_VIDEO                1248
#define IDC_CHECKPSK                    1249
#define IDC_BUTTON_LED                  1250
#define IDC_CHECK1                      1251
#define ID_STARTSYS                     32772
#define ID_MENUSTART                    32775
#define ID_MENUCLOSEPC104               32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        243
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1252
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
